use serde_repr::Deserialize_repr;
use num_derive::ToPrimitive;

mod official;
mod workshop;

#[derive(Debug, Deserialize_repr, ToPrimitive)]
#[repr(u8)]
pub enum LevelDifficulty {
    Casual,
    Normal,
    Advanced,
    Expert,
    Nightmare,
    None,
}

#[allow(non_camel_case_types)]
#[derive(Debug, Deserialize_repr, ToPrimitive)]
#[repr(u16)]
pub enum MusicCueId {
    None,
    Grime,
    Engage,
    KaBamSon,
    Momenta,
    TheAlliance,
    Continuum,
    Drive,
    GroundZero,
    ColdWind,
    Halloween,
    Corruption,
    Storm,
    The_Tunnel = 15,
    Darkness_Intense,
    WereLivingInASociety,
    RandomChordSomething,
    Aftermath,
    TheMonolith,
    FadedAway = 26,
    DarknessSlight,
    Spectrum,
    GZLight,
    GZGate,
    GZInsane,
    CarolOfTheBells,
    DigitalApathy,
    TheManor,
    DevValue_ = 1000,
    FFTTestLoop,
    IntroCutscene,
    AftermathLoop,
    Continuum2,
    GZInsaneSlow,
    TunnelHorror,
    SpectrumSlow,
    IntroCutsceneV2,
    NewBSAmbient,
    Convolution,
    Forge,
    DarknessIntenseV2,
    NSFinalBoot,
    Scratch,
    Flip,
    NegativeSpace,
    Abstraction,
    ForgeLoop,
    GrimeLoop,
    AbstractionLoop,
    AbstractionStrings,
    AbstractionStringsDU,
    DUEnding,
    AbandonedUtopia,
    DeeperIntoTheVoid,
    Low,
    Ambient2,
    EchoesIntro,
    TepidPants,
    Violent,
    Belly,
    Perfect,
    Sentinel,
    EchoesStorm,
    Void,
    Isolation,
    IsolationReturn,
    SecretTeleport,
    Echoes = 1040,
    EnemyIntro,
    DarkWind,
    Machine17,
    Machine17Remix,
    Observatory,
    Resonance,
    Deterence,
    Terminus,
    Mobilization,
    Collapse,
    TheOtherSide,
    twoHOTtwoPANTS,
}
